# Change these first
owner: rglauco # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sito Web
    url: https://www.comune.preganziol.tv.it
  - name: Servizi Online
    url: https://servizionline.comune.preganziol.tv.it
  - name: Zimbra
    url: https://posta.comune.preganziol.tv.it
  - name: NextCloud
    url: https://nc.comune.preganziol.tv.it
  - name: Cool Jconon
    url: https://concorsi.comune.preganziol.tv.it
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Statistiche uptime siti web"
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
